name: Test Game Build

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Test Web Build
        run: |
          mkdir -v -p build/test
          godot --headless --verbose --export-release "Web" build/test/index.html
      
      - name: Validate Build
        run: |
          if [ ! -f "build/test/index.html" ]; then
            echo "Build failed: index.html not found"
            exit 1
          fi
          
          if [ ! -f "build/test/index.js" ]; then
            echo "Build failed: index.js not found"
            exit 1
          fi
          
          if [ ! -f "build/test/index.wasm" ]; then
            echo "Build failed: index.wasm not found"
            exit 1
          fi
          
          echo "Build validation successful!"
      
      - name: Check File Sizes
        run: |
          echo "Build file sizes:"
          ls -lh build/test/
          
          # Check if files are reasonable size (not empty, not too large)
          html_size=$(stat -c%s "build/test/index.html")
          js_size=$(stat -c%s "build/test/index.js")
          wasm_size=$(stat -c%s "build/test/index.wasm")
          
          if [ $html_size -lt 1000 ]; then
            echo "Warning: HTML file seems too small ($html_size bytes)"
          fi
          
          if [ $js_size -lt 10000 ]; then
            echo "Warning: JS file seems too small ($js_size bytes)"
          fi
          
          if [ $wasm_size -lt 100000 ]; then
            echo "Warning: WASM file seems too small ($wasm_size bytes)"
          fi
          
          echo "File size check completed"